travis:
  secure:
    BINSTAR_TOKEN: X1LBcs4YWDGV6cBHb5DS9W3f4in+6cb2+rPhhxEXNu8YYSNYnUDH7dUl3VYuBAFr2JigAfrD4ajdaDQ0QMcy/iwj6jbuQD1DUNh+sd7aAcS05XiHjoiVkWREvgoJNgTHkayXoPfJCHUzUHxU03N3TRkWOBVCMH4bgBycM5k4vPwzmkQjJvDx/4IFS7CAphg78mQ5q4pA+O3Pi/GlEds92HyU6hdDUmeqSPCsRxokZjRh3jlEtxCn1wjQ70t2S/81F6MfknuDcn5Wer6ec229phcgtJS8LALB7n3dk6bHD24sCGivkL/175W/wlUQGe+cIrK9LlgVRJ86KH/sHr6x0I/0SDYQOFnRGbAcRYPHw9HZvjGASdKw4uUxQwW6Pkyc6/iKEFfmsEdP2KuWyTN+CAosg7TDJi3dp9Tx2TnSpEykAjRI9/L4IGbDDrVEH/1DNusnFa1rM7wPfV0pUT8LWeZS8pOi+oK6YUjLsMC3AX3RYvykrZZ5SfVAbPXObMUDc+ml2P9HNZ0LY/0/zHl6oVZVL8YGnEZ2bBIjkTP0nKuf8F6qvYCPk9y0ctAEOEXmS5d3nOeqTcN86/aghZ8+WLkxeQeJdTZNeEhz9pNsKsib6kJgNRjwVF+i+WhtmcNKxyqZBrslMeXYLIHlnnCIv12GRNe4XIMmWkFssP6LrY0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
