travis:
  secure:
    BINSTAR_TOKEN: ihv9F7mCekMy2pInOBxKwKKCEfzk0E5FRTgZlUBUnyt+vjbBGJxOlDM1HtpVye+KkSgSjBXl8Bvwtn+FyiTC+kcJPONv7TrbSvDaSC3kgM0qN3J2Ma7+L8P6ltTu2xYITJEo+VoOfa1XkL6/sFXawO0xDROT7woukN5xAO68ZVlmnJZPPMGZZkZh2JrA0AfcPcqK5rDq0KMEAbCDNsck7MmEuHEj9qkIMFrvsMSEniGnHTszQ4arTdUPmc+XygegfCLnjLV2Z55br0geR/IU8b2bBPNIRnmu6Lk6Z2BfJQaAHUpmY0IWsnKMVAsgmG6303Cl44Nhg31KPVhcg3wgforEvlQnli6tKXlXsrg2Itlp+RVcae9x1iR9+/JzGJTTgiNF5hdnB/JcZ4K6evJQ+z6zmWDw6jTQpxu1aCYwJyuuLqCIQpreN72HsnCrdrCl+IA6HtIsCcW2T3hudPC6TifE4vZtejpK1Rylepc9WlAJmFr/hs9mt/G+T5h/wevI3Hyl/JAcJBZ2Dp8GQOiET61SFg13PUsxv9gRxgF3SmR6NvorYw5RZvv466Rt+GPpAy9wYOSVmI+vy1sYAOxH+M5NTEcPTIValmSfJPM+gre6OENUDzHYx7IecVajD07L7xysy2+9BVdnSKpjeb5wd2MaO03gljlo8q2clvcpwpY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
